### ISSUE TITLE
Links between images and Dockerfiles 

### ISSUE THREAD

**Issue by eitsupi** [conda-forge/miniforge-images#6]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
When I searched for a Docker image of Miniforge, it took me a while to get to this repository.
It would be very helpful if you put a link to dockerhub like [conda-forge / docker-images](https://github.com/conda-forge/docker-images), and write in the README which images are defined in this repository. 

There is not much information on the dockerhub side, too...
![image](https://user-images.githubusercontent.com/50911393/112825843-35c61e00-90c7-11eb-94d7-9d193d033230.png)

**Comment by xhochy** [comment]
Added a description to all repositories.
